spring:
  application:
    name: chatAiDemo
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: deepseek-r1:8b
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: qwen-turbo

logging:
  level:
    org.springframework.ai.chat.client.advisor: DEBUG
    com.touhouqing.chatAiDemo: DEBUG