spring:
  application:
    name: chatAiDemo
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: deepseek-r1:8b
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: qwen-turbo
          temperature: 0.5
  datasource:
    url: jdbc:mysql://localhost:3306/chatAiDemo?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    org.springframework.ai: DEBUG
    com.touhouqing.chatAiDemo: DEBUG